### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by boneskull** [popomore/github-labels#16]
What do I have to do vis-a-vis the GitHub API (OAuth tokens, etc) if I want to fork this and contribute some code?  I'm having various issues where my tokens become invalid or my connections are refused.  Do I need to register my fork with GitHub or something?

**Comment by popomore** [comment]
Sorry, I miss this issue. You can create a test repo that you can access, then you can do everything.

**Comment by boneskull** [comment]
I don't think that really answered my question, but I don't remember what problem(s) I was having.
