### ISSUE TITLE
Cannot create labels

### ISSUE THREAD

**Issue by jbenhamou** [popomore/github-labels#21]
## Coordinates:

MacOX - 10.11.6 
NPM - 3.10.5

## Issue

I'm getting an error when running the command with private or public Git repository owned by an organization as follows:

```
$ labels -c conf.json icoe-labs/labels-test-public
/usr/local/lib/node_modules/github-labels/bin/labels:5
const program = require('commander');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I tried to install commander with the following outcomes:

```
$ npm install commander
/Users/yoni
└── commander@2.9.0 

npm WARN enoent ENOENT, open '/Users/yoni/package.json'
npm WARN yoni No description
npm WARN yoni No repository field.
npm WARN yoni No README data
npm WARN yoni No license field.
[~/dev/icoe-labs/labels-test] (master #)
```

Running the labels command afterwards results in same error as before installing commander (I'm assuming commander was installed in-spite of the WARN messages)

**Comment by popomore** [comment]
Please check your node version, it should be > 4
Jonathan Ben-Hamou <notifications@github.com>于2016年9月1日 周四下午2:33写道：

**Comment by jbenhamou** [comment]
Yes your suggestion worked.

I had to run:
```
npm install -g n
sudo n stable
```

Thanks for the quick response
